name: Build ZMK firmware
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3
include:
- board: nice_nano_v2
- shield: corne_left
+ shield: corne_left nice_view_adapter nice_view
- board: nice_nano_v2
- shield: lily58_right
+ shield: corne_right nice_view_adapter nice_view
